### ISSUE TITLE
reuse templates

### ISSUE THREAD

**Issue by maciogg** [dus4nstojanovic/create-files-from-template-vscode#2]
Can I configure the plugin to use the same templates in several different projects? When I do "New from template" for the first time in a new project, it creates a .cfft.templates directory in that project and I have to copy the templates from another project where I used them before.

**Comment by DusanStojanovic-gowago** [comment]
Hi! Thank you for asking!

Unfortunately, the desired feature is not currently available. 

However, I liked it. I will consider implementing it shortly.

**Comment by maciogg** [comment]
I'm looking forward to it :) I really like the extension and there's only one functionality missing.

**Comment by dus4nstojanovic** [comment]
Hey @maciogg. The requested feature has been implemented and published in the 1.8.0 version. Feel free to upgrade your extension and try it out. 

You should be able to find the new setting if you search for the `CFFT: Root Folder`:
![image](https://github.com/user-attachments/assets/422ffe28-291f-4225-9fe1-a794a763cdd0)

Or you could edit the .vscode/settings.json by adding the following line: 
```json
"CFFT.rootFolder": "path-to-your-folder",
```

The path you provide can be whatever you prefer - relative, or absolute.

Please read the readme for more info [here](https://marketplace.visualstudio.com/items?itemName=DusanStojanovic.cfft#reuse-configurations-and-templates-across-multiple-projects).
