### ISSUE TITLE
How to disable "Enter file name"

### ISSUE THREAD

**Issue by maciogg** [dus4nstojanovic/create-files-from-template-vscode#3]
Have simply asset folder with subfolder. No need to input file name. How to disable this prompt?

    {
      "name": "asset",
      "description": "Create an asset folder with subfolders",
      "options": {
        "templatePath": "/.cfft.templates/asset",
        "dirPath": "./asset",
        "fileNameTextToBeReplaced": "asset",
        "shouldReplaceFileName": false,
        "shouldReplaceFileContent": false
      }
    }

**Comment by DusanStojanovic-gowago** [comment]
If both “shouldReplaceFileName” and “shouldReplaceFileContent” are false, and there are no “searchAndReplace” items or anything that should be replaced, the extension should probably skip asking for the file name step. 

I will revisit this next week, and check what should be done.

**Comment by dus4nstojanovic** [comment]
The issue has been fixed in the version `1.8.0`. Feel free to try it out.

The app won't prompt the file name question if you provide the same configuration - since the `shouldReplaceFileName` is `false`, and the `{fileName}` placeholder is not used in the options.
